### ISSUE TITLE
Erro no make me

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-UY#4]
Erro no make me

Link
https://github.com/digital-guard/preserv-UY/tree/main/data/_pk0002.01

make me pg_db=ingest20

```
-- Generating makefile --
cd /var/gits/_dg/preserv/src; make generate_makefile country=UY pack_id=2.1 baseSrcPack=/var/gits/_dg/preserv-UY/data/_pk0002.01 baseSrc=/var/gits/_dg output=/tmp/pg_io/tmpfile_UY2.1
make[1]: Entering directory '/var/gits/_dg/preserv/src'
-- Generating makefile in /tmp/pg_io/tmpfile_UY2.1 --
NOTICE:  codec_desc_global : {"srid": "4326"}
NOTICE:  layer : geoaddress, method: csv2sql
NOTICE:  codec resultante : {"srid": "4326"}
NOTICE:  codec_extension from method: <NULL>
ERROR:  TypeError: the JSON object must be str, bytes or bytearray, not NoneType
CONTEXT:  Traceback (most recent call last):
  PL/Python function "jsonb_mustache_render", line 4, in <module>
    j = json.loads(i)
  PL/Python function "jsonb_mustache_render", line 338, in loads
PL/Python function "jsonb_mustache_render"
SQL statement "SELECT replace(jsonb_mustache_render(mkme_tpl, optim.jsonb_mustache_prepare(p_yaml)),E'\u130C9',$$\"$$)"
PL/pgSQL function optim.generate_makefile(text,text,text,text,text) line 16 at SQL statement
make[1]: *** [makefile:224: generate_makefile] Error 1
make[1]: Leaving directory '/var/gits/_dg/preserv/src'
make: *** [makefile:40: me] Error 2



```

**Comment by 0e1** [comment]
Problema causado pelo preenchimento errado de donor.csv e donatePack.csv.

Todo o donor **deve** ter um _vatid_ (ou equivalente) (todo donor deve ter existência legal comprovada). No caso do Uruguai um _RUT_. Por favor, fornecer o RUT do donor. Notar que adicionei o _wikidata_id_ dele. O RUT eu não encontrei. É possível consultar um RUT em https://servicios.dgi.gub.uy/serviciosenlinea/dgi--servicios-en-linea--consulta-de-certifcado-unico, desde que se saiba o RUT. 

Em Peru (RUC) e Chile (RUT), eu encontrei os _vatid_ que faltavam. Mas é preciso verificá-los com os números que possuem. No caso do Peru é possível buscar em https://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/FrameCriterioBusquedaWeb.jsp.


Lembrar que, após atualizações em donor e donatepack deve-se executar:

```sh
pushd /var/gits/_dg/preserv/src
make load_optim_csv pg_datalake=dl03t_main
popd
```
Sem isso, os novos dados não estarão disponíveis para o _make_ usar. Obviamente, vai funcionar se os arquivos donor.csv.e donatepack.csv não estiverem com algum problema no preenchimento.

Agora, o `make me` está funcionando para [_pk0002.01](https://github.com/digital-guard/preserv-UY/tree/main/data/_pk0002.01), apesar de `vat_id=vatid:`. Novamente, esse número é importante para o esquema de doação/preservação proposto.

**Comment by crebollobr** [comment]
@luisfelipebr consegue ajudar nessa questão de documentos de outros países?

**Comment by ppKrauss** [comment]
@luisfelipebr e @crebollobr , só serão publicados pacotes com dados completos, **o "donor" precisa ser identificado** com CNPJ (vatID)  e/ou Wikidata.
