### ISSUE TITLE
Ingestão de house_number

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-UY#5]
Aparentemente não está sendo feito a ingestão de house_number

LINKS
https://github.com/digital-guard/preservCutGeo-UY2021/tree/correio-20221207/data/_pk0002.01/geoaddress
https://github.com/digital-guard/preserv-UY/tree/main/data/_pk0002.01

**Comment by 0e1** [comment]
De fato, não está.

O problema está em `sql_view`, na concatenação `num_puerta || ' ' || letra_puerta` ao concatenar com valor _null_.

Aplicar [COALESCE](https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL) no campos deve resolver: coalesce(campo,'').

Com isso, terá que refazer a ingestão e a publicação.

**Comment by crebollobr** [comment]
Usei concat
https://stackoverflow.com/questions/34934762/string-concatenation-with-a-null-seems-to-nullify-the-entire-string-is-that-de/47564272#47564272?newreg=e16bc5be63ab4a42878022dc991b5fbf


![image](https://user-images.githubusercontent.com/22559999/209820131-f6c18ef4-13d1-4e3b-9d22-81300c59943e.png)

**Comment by crebollobr** [comment]
Aparentemente os pontos estão no lote e não na frente do lote

**Comment by crebollobr** [comment]
Novo link

https://github.com/digital-guard/preservCutGeo-UY2021/tree/correio-20221228/data/_pk0002.01/geoaddress

**Comment by 0e1** [comment]
Lembrar de executar o [passo](https://github.com/digital-guard/preserv/wiki/Testes-reais-para-garantia-de-software-no-servidor-produtivo#copiar-informa%C3%A7%C3%B5es-para-dl03t_main), antes de apagar a ingest.

Se não quiser executar o passo, tudo bem. Apenas informar a ingest que foi utilizada e não apagá-la.

**Comment by crebollobr** [comment]
Resultado:
```
carlos@addressforall:/var/gits/_dg/preserv/src$ make to_donated_packcomponent pg_db=ingest20 pg_datalake=dl03t_main
--- DUMP ingest.donated_packcomponent to /tmp/pg_io/dump_component_ingest20.sql ---
pg_dump --column-inserts --data-only -t ingest.donated_packcomponent postgres://postgres@localhost/ingest20 > /tmp/pg_io/dump_component_ingest20.sql
--- Preparing /tmp/pg_io/dump_component_ingest20.sql ---
bash to_donated_packcomponent.bash /tmp/pg_io/dump_component_ingest20.sql
--- INSERT /tmp/pg_io/dump_component_ingest20.sql INTO dl03t_main optim.donated_PackComponent_not_approved ---
grep "INSERT INTO" /tmp/pg_io/dump_component_ingest20.sql | psql postgres://postgres@localhost/dl03t_main
INSERT 0 1
--- See optim.donated_PackComponent_not_approved in dl03t_main ---

```

**Comment by 0e1** [comment]
Merge realizado.
